# Global LLM configuration
[llm]
model = "ep-20250212141905-2grjj"
base_url = "https://ark.cn-beijing.volces.com/api/v3"
api_key = "6104005d-fdfb-4e88-b303-0befeff71dee"
max_tokens = 8192 
temperature = 0.0

# Optional configuration for specific LLM models
[llm.vision]
model = "ep-20250212141905-2grjj"
base_url = "https://ark.cn-beijing.volces.com/api/v3"
api_key = "6104005d-fdfb-4e88-b303-0befeff71dee"
