# Global LLM configuration
[llm]
model = "doubao-pro-32k-functioncall-241028"
base_url = "https://ark.cn-beijing.volces.com/api/v3"
api_key = "6104005d-fdfb-4e88-b303-0befeff71dee"
max_tokens = 4096
temperature = 0.0

# Optional configuration for specific LLM models
[llm.vision]
model = "doubao-pro-32k-functioncall-241028"
base_url = "https://ark.cn-beijing.volces.com/api/v3"
api_key = "6104005d-fdfb-4e88-b303-0befeff71dee"
